Inventory/Models/Reporte.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Inventory.Models
{
    public class Reporte
    {
        public List<Reporte> Reportedisp { get; set; }

        [Key]
        public int ReporteId { get; set; }

        [Required(ErrorMessage = "El campo {0} es obligatorio")]
        [DataType(DataType.Date)]
        [Display(Name = "Fecha desde")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]


        public DateTime FechaInicio { get; set; }

        [Required(ErrorMessage = "El campo {0} es obligatorio")]
        [DataType(DataType.Date)]
        [Display(Name = "Fecha hasta")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime FechaFinal { get; set; }


        [Range(1, double.MaxValue, ErrorMessage = "Debe seleccionar un Estado ")]
        [Display(Name = "Estado")]
        public int EstadoId { get; set; }

        [Display(Name = "Estado")]
        public string Estatus { get; set; }

        public string Identificador { get; set; }

        [Display(Name = "Dispositivo")]
        public string Nombre { get; set; }

        [Display(Name = "Marca")]
        public string Marca { get; set; }

        [Display(Name = "Modelo")]
        public string Modelo { get; set; }

        [Display(Name = "Precio")]
        public string Precio { get; set; }

        [Display(Name = "Serial")]
        public string Serial { get; set; }
       
        [DataType(DataType.Date)]
        [Display(Name = "Fecha de compra")]
        public DateTime Fecha { get; set; }

        public string Sede { get; set; }

        public string Laboratorio { get; set; }


        [Range(1, double.MaxValue, ErrorMessage = "Debe seleccionar una sede ")]
        public int SedeId { get; set; }
        [Range(1, double.MaxValue, ErrorMessage = "Debe seleccionar un laboratorio ")]
        public int LaboratorioId { get; set; }

        public int UsuarioId { get; set; }

        //public virtual ICollection<Dispositivo> Dispositivos { get; set; }



    }
}

Inventory/Controllers/ReportesController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CrystalDecisions.CrystalReports.Engine;
using Inventory.Clases;
using Inventory.Models;

namespace Inventory.Controllers
{
   
    public class ReportesController : Controller
    {
        private InventoryContext db = new InventoryContext();

       
        // GET: Reportes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Reporte reporte = db.Reportes.Find(id);

            if (reporte == null)
            {
                return HttpNotFound();
            }

            return View(reporte);
        }


        // GET: Reportes/Create
        public ActionResult Create()
        {
            var autentic = User.Identity.IsAuthenticated;
            var nametemp = User.Identity.Name;
            var usutemp = db.Usuarios.Where(s => s.Logueo.Equals(nametemp)).FirstOrDefault();

            MetodosHelper.EliminaReporte(usutemp.Usuarioid);           

            //Iniciar con la fecha del sistema
            Reporte model = new Reporte() { Reportedisp = new List<Reporte>() };
			{
				model.FechaInicio = System.DateTime.Now;
				model.FechaFinal = System.DateTime.Now;
			};

            if(usutemp.Rol == "false")
            {
                model.SedeId = usutemp.SedeId;
                model.LaboratorioId = usutemp.LaboratorioId;
            }
			else
			{
				usutemp = db.Usuarios.Where(s => s.Logueo.Equals(nametemp)).FirstOrDefault();
			}		

            ViewBag.LaboratorioId = new SelectList(
                CombosHelper.GetLaboratorios(),
                "LaboratorioId",
                "Nombre");

            ViewBag.SedeId = new SelectList(
                CombosHelper.GetSedes(),
                "SedeId",
                "Nombre");

            ViewBag.EstadoId = new SelectList(
                            CombosHelper.GetEstados(),
                            "EstadoId",
                            "Nombre");			

            return View(model);
        }


        public JsonResult GetLaboratorios(int sedeid)
        {
            db.Configuration.ProxyCreationEnabled = false;
            var laboratorios = db.Laboratorios.Where(c => c.SedeId == sedeid);
            return Json(laboratorios);
        }


        // POST: Reportes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Reporte rep )
        {            
			var com = 0;

            Reporte reporvista = new Reporte() { Reportedisp = new List<Reporte>() };

            if (ModelState.IsValid)
            {
                var autentic = User.Identity.IsAuthenticated;
                var nametemp = User.Identity.Name;
                var usutemp = db.Usuarios.Where(s => s.Logueo.Equals(nametemp)).FirstOrDefault();
                            
                var dispousuarios = db.Dispositivos.Where(d => d.EstadoId == rep.EstadoId && d.Fecha >= rep.FechaInicio && d.Fecha <= rep.FechaFinal && d.LaboratorioId == rep.LaboratorioId && d.SedeId == rep.SedeId).ToList();
                               
                foreach (var req in dispousuarios)
                {
                    Reporte report = new Reporte()
                    {
                        FechaFinal = rep.FechaFinal,
                        FechaInicio = rep.FechaInicio,
                        EstadoId = rep.EstadoId,
                        Estatus = db.Estados.Where(e => e.EstadoId == req.EstadoId).Select(e => e.Nombre).FirstOrDefault(),
                        Identificador = req.Identificador,
                        Nombre = req.Nombre,
                        Marca = req.Marca,
                        Modelo = req.Modelo,
                        Precio = req.Precio.ToString(),
                        Serial = req.Serial,
                        Fecha = req.Fecha,
                        Sede = db.Sedes.Where(s => s.SedeId == req.SedeId).Select(s => s.Nombre).FirstOrDefault(),
                        Laboratorio = db.Laboratorios.Where(l => l.LaboratorioId == req.LaboratorioId).Select(l => l.Nombre).FirstOrDefault(),
                        SedeId = rep.SedeId,
                        LaboratorioId = rep.LaboratorioId,
                        UsuarioId = usutemp.Usuarioid
                    };
                                            
                    if (report != null)
					{
						com = com + 1;
					}

                    db.Reportes.Add(report);
                    db.SaveChanges();
                }

				if (com == 0)
				{
                    ViewBag.Message = "No hay registros con el estado seleccionado";
				}

                // carga los registros para mostrar en la vista
				foreach (var req in db.Reportes.Where(u => u.UsuarioId == usutemp.Usuarioid).ToList())
                {
                    Reporte reporttmp = new Reporte();

                    reporttmp.FechaFinal = rep.FechaFinal;
                    reporttmp.FechaInicio = rep.FechaInicio;
                    reporttmp.EstadoId = rep.EstadoId;
                    reporttmp.Estatus = req.Estatus;
                    reporttmp.Identificador = req.Identificador;
                    reporttmp.Nombre = req.Nombre;
                    reporttmp.Marca = req.Marca;
                    reporttmp.Modelo = req.Modelo;
                    reporttmp.Precio = req.Precio;
                    reporttmp.Serial = req.Serial;
                    reporttmp.Fecha = req.Fecha;
                    reporttmp.Sede = req.Sede;
                    reporttmp.Laboratorio = req.Laboratorio;

                    reporvista.Reportedisp.Add(reporttmp);
                }

                //Se realiza el registro del evento para temas de seguridad y trazabilidad      
                if (autentic)
                {
                    var eventtemp = new Eventos();
                    var esttmp = db.Estados.Where(e => e.EstadoId == rep.EstadoId).Select(n => n.Nombre).FirstOrDefault();

                    eventtemp.Fechcha = System.DateTime.Now;
                    eventtemp.UsuarioId = usutemp.Usuarioid;
                    eventtemp.Descripcion = "El usuario logueado genero un reporte de dispositivos de estado " + esttmp + ".";

                    db.Eventos.Add(eventtemp);
                    db.SaveChanges();
                }                
            }

			var id = rep.SedeId;

            ViewBag.EstadoId = new SelectList(
                 CombosHelper.GetEstados(),
                    "EstadoId",
                     "Nombre");
           
            ViewBag.LaboratorioId = new SelectList(
                    CombosHelper.GetLaboratoriosed(id),
                    "LaboratorioId",
                    "Nombre");

            ViewBag.SedeId = new SelectList(
                CombosHelper.GetSedes(),
                "SedeId",
                "Nombre");

            return View(reporvista);                        
        }


        //Metodo para generar y exportar el archivo en formato pdf
        public ActionResult PDF()
        {
            var reportdisp = this.GenerarReporteDisp();
            var stream = reportdisp.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);

            //Se realiza el registro del evento para temas de seguridad y trazabilidad
            var autentic = User.Identity.IsAuthenticated;
            var eventtemp = new Eventos();

            if (autentic)
            {
                var nametemp = User.Identity.Name;
                var usutemp = db.Usuarios.Where(s => s.Logueo.Equals(nametemp)).FirstOrDefault();

                eventtemp.Fechcha = System.DateTime.Now;
                eventtemp.UsuarioId = usutemp.Usuarioid;
                eventtemp.Descripcion = "El usuario logueado realizo la exportacion del reporte a formato pdf ";

                db.Eventos.Add(eventtemp);
                db.SaveChanges();
            }
			
			return File(stream, "application/pdf");
		}

       
        //Metodo que realiza la consulta de la informacion del reporte en la base de datos 
        private ReportClass GenerarReporteDisp()
        {    
            var autentic = User.Identity.IsAuthenticated;
            var nametemp = User.Identity.Name;
            var usutemp = db.Usuarios.Where(s => s.Logueo.Equals(nametemp)).FirstOrDefault();

            var Id = usutemp.Usuarioid;

            //como para el reporte no se conecta por entitiframework se debe hacer por ado
            var connectionString = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
            var connections = new SqlConnection(connectionString);
            var dataTable = new DataTable();
            var sql = "select * from Reportes where UsuarioId = @Id ORDER BY Nombre";

            try
            {
                connections.Open();
                // en estas lineas se envia la instruccion sql con el parametro id para generar el reporte solo con lo relacionado al usuario logueado
                var conmand = new SqlCommand(sql, connections);

                conmand.Parameters.Add("@Id", SqlDbType.Int);
                conmand.Parameters["@Id"].Value = Id;

                var adapter = new SqlDataAdapter(conmand);

                adapter.Fill(dataTable);  
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }

            var report = new ReportClass();

            report.FileName = Server.MapPath("/Reports/ReporteDispo.rpt");
            report.Load();
            report.SetDataSource(dataTable);

			MetodosHelper.EliminaReporte(usutemp.Usuarioid);

			return report;
        }
                 

Inventory/Views/Reportes/Create.cshtml
@model Inventory.Models.Reporte
@{
    ViewBag.Title = "Create";
}
<hr style="border-color:white" />
<h2>Generar Reporte</h2>
@if (ViewBag.Message != null)
{

    <script type="text/javascript">window.onload = function () { alert("@ViewBag.Message"); };</script>
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">


        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <hr style="border-color:black" />
        @if (this.User.IsInRole("Usuario"))
        {
            @Html.HiddenFor(model => model.LaboratorioId)
            @Html.HiddenFor(model => model.SedeId)
        }
            <div class="row">
                <div class="col-md-6">
                    <h4>Elija las fechas de compra</h4>

                    <div class="form-group">
                        @Html.LabelFor(model => model.FechaInicio, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.FechaInicio, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.FechaInicio, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group">
                        @Html.LabelFor(model => model.FechaFinal, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.FechaFinal, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.FechaFinal, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group">
                        @Html.LabelFor(model => model.EstadoId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("EstadoId", null, htmlAttributes: new { @class = "form-control" })

                            @Html.ValidationMessageFor(model => model.EstadoId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    @if (this.User.IsInRole("Administrador"))
                    {

                        <div class="form-group">
                            @Html.LabelFor(model => model.SedeId, "Sede", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("SedeId", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.SedeId, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.LaboratorioId, "Laboratorio", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("LaboratorioId", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.LaboratorioId, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    }
                </div>



                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Agregar al reporte" class="btn btn-primary" />
                            @*@Html.ActionLink("Regresar", "Index", "Home", new { }, new { @class = "btn btn-default" })
                            @Html.ActionLink("Exportar Reporte", "PDF", new { }, new { @class = "btn btn-default", target = "_blank" })*@

                        </div>
                    </div>



                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            @Html.ActionLink("Exportar Reporte", "PDF", new { }, new { @class = "btn btn-default", target = "_blank" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            @Html.ActionLink("Limpiar campos", "Create", "Reportes", new { }, new { @class = "btn btn-primary" })
                        </div>
                    </div>





                </div>

            </div>
        </div>



    <h2>Detalles del reporte</h2>

    <table class="table table-bordered table-striped mb-none" id="datatable-default">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Identificador)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Estatus)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Laboratorio)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Sede)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Fecha)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Marca)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Modelo)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Precio)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Serial)
                </th>

            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model.Reportedisp)
            {
                <tr>

                    <th>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </th>
                    <th>
                        @Html.DisplayFor(modelItem => item.Identificador)
                    </th>
                    <th>
                        @Html.DisplayFor(modelItem => item.Estatus)
                    </th>
                    <th>
                        @Html.DisplayFor(modelItem => item.Laboratorio)
                    </th>
                    <th>
                        @Html.DisplayFor(modelItem => item.Sede)
                    </th>
                    <th>
                        @Html.DisplayFor(modelItem => item.Fecha)
                    </th>
                    <th>
                        @Html.DisplayFor(modelItem => item.Marca)
                    </th>
                    <th>
                        @Html.DisplayFor(modelItem => item.Modelo)
                    </th>
                    <th>
                        @Html.DisplayFor(modelItem => item.Precio)
                    </th>
                    <th>
                        @Html.DisplayFor(modelItem => item.Serial)
                    </th>


                </tr>
            }
        </tbody>

    </table>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            $("#SedeId").change(function () {
                $("#LaboratorioId").empty();
                $("#LaboratorioId").append('<option value=" 0 ">[Elija un Laboratorio...]</option>');
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("GetLaboratorios")',
                    dataType: 'json',
                    data: { sedeid: $("#SedeId").val() },
                    success: function (data) {
                        $.each(data, function (i, data) {
                            $("#LaboratorioId").append('<option value="'
                                + data.LaboratorioId + '">'
                                + data.Nombre + '</option>');
                        });
                    },
                    error: function (ex) {
                        alert('Failed to retrieve sedes.' + ex);
                    }
                });
                return false;
            })
        });
    </script>
}

Inventory/Views/Reportes/Delete.cshtml
@model Inventory.Models.Reporte

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Reporte</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Estutus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estutus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Identificador)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Identificador)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Marca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Serial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Serial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sede)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sede)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Laboratorio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Laboratorio)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Inventory/Views/Reportes/Details.cshtml
@model Inventory.Models.Reporte

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Reporte</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Estutus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estutus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Identificador)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Identificador)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Marca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Serial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Serial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sede)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sede)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Laboratorio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Laboratorio)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ReporteId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Inventory/Views/Reportes/Edit.cshtml
@model Inventory.Models.Reporte

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Reporte</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ReporteId)

        <div class="form-group">
            @Html.LabelFor(model => model.Estutus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estutus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estutus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Identificador, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Identificador, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Identificador, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Marca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Modelo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Modelo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Modelo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Serial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Serial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Serial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sede, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sede, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sede, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Laboratorio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Laboratorio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Laboratorio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}