Inventory/Controllers/ValidacionesController.cs
using CrystalDecisions.CrystalReports.Engine;
using Inventory.Clases;
using Inventory.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Inventory.Controllers
{
    public class ValidacionesController : Controller
    {
        private InventoryContext db = new InventoryContext();

        //metodo que exporta el reporte a un archivo en formato pdf y lo muestra en una pestaña del navegador
        public ActionResult PDF()
        {

            var autentic = User.Identity.IsAuthenticated;
            var nametemp = User.Identity.Name;
            var usutemp = db.Usuarios.Where(s => s.Logueo.Equals(nametemp)).FirstOrDefault();

            // segun el id del usuario consulta en la cabecera de la validacion si existen las firmas
            var validafirma = db.Validaciones.Where(u => u.UsuarioId == usutemp.Usuarioid).Select(f => f.Firmausuario1).FirstOrDefault();

            // si no existen las firmas se carga un mensaje para motrarlo en el reporte vacio
            if (validafirma == null)
            {
                ReporteValidacion reportfinaltmp = new ReporteValidacion();

                reportfinaltmp.ObservacionFirmas = "Debe agregar las firmas antes de exportar el reporte de validacion";
                reportfinaltmp.Fecha_compra = " ";
                reportfinaltmp.Precio = " ";


                db.ReporteValidaciones.Add(reportfinaltmp);
                db.SaveChanges();
            }

            // consulta la informacion necesaria para el reporte
            string ruta1 = db.Validaciones.Where(u => u.UsuarioId == usutemp.Usuarioid).Select(f => f.Firmausuario1).FirstOrDefault();
            string ruta2 = db.Validaciones.Where(u => u.UsuarioId == usutemp.Usuarioid).Select(f => f.Firmausuario2).FirstOrDefault();
            string path1 = string.Empty;
            string path2 = string.Empty;
            path1 = Server.MapPath(ruta1);
            path2 = Server.MapPath(ruta2);

            var reportdisp = this.GenerarReporteVali();

            reportdisp.SetParameterValue("Firma1", path1);
            reportdisp.SetParameterValue("Firma2", path2);

            // realiza la exportacion del eporte
            var stream = reportdisp.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);

            //Se realiza el registro del evento para temas de seguridad y trazabilidad
            var eventtemp = new Eventos();

            if (autentic)
            {

                eventtemp.Fechcha = System.DateTime.Now;
                eventtemp.UsuarioId = usutemp.Usuarioid;
                eventtemp.Descripcion = "El usuario logueado realizo la exportacion del reporte de validacion a formato pdf ";

                db.Eventos.Add(eventtemp);
                db.SaveChanges();
                
            }
            
            // se borra el contenido de las tablas del reporte
            if (validafirma != null)
            {

                MetodosHelper.EliminarValDetaTmp(usutemp.Usuarioid);
                MetodosHelper.EliminarRepVal(usutemp.Usuarioid);
               
                foreach (var dtmp in db.Dispositivos.Where(u => u.LaboratorioId == usutemp.LaboratorioId))
                {
                    dtmp.EstadoInventario = "No Inventariado";
                    dtmp.Observaciones = "";
                    db.Entry(dtmp).State = EntityState.Modified;
                    
                }
                
                db.SaveChanges();

                Validador validacion = db.Validaciones.Where(u => u.UsuarioId == usutemp.Usuarioid).FirstOrDefault();

                validacion.Firmausuario1 = null;
                validacion.Firmausuario2 = null;
                db.Entry(validacion).State = EntityState.Modified;
                db.SaveChanges();

            }

            // lleva a una nueva ventana en la que muestra el reporte
            return File(stream, "application/pdf");

        }

        
        // Get Firmar validacion muestra formulario para ingresar las imagenes de las firmas
        public ActionResult FirmarValidacion(int? id)
        {

            // se utiliza el parametro id para validar si se registraron las firmas en el metodo post previamente
            if (id != null)
            {

                ViewBag.Message = "Las firmas ya fueron guardadas con anterioridad, por favor hacer la exportacion del reporte";

            }

            var autentic = User.Identity.IsAuthenticated;
            var nametemp = User.Identity.Name;
            var usutemp = db.Usuarios.Where(s => s.Logueo.Equals(nametemp)).FirstOrDefault();

            Validador validacion = db.Validaciones.Where(u => u.UsuarioId == usutemp.Usuarioid).FirstOrDefault();

            if (validacion == null)
            {

                return HttpNotFound();

            }

            validacion.Fecha = System.DateTime.Now;
            validacion.UsuarioId = usutemp.Usuarioid;
            validacion.SedeId = usutemp.SedeId;
            validacion.LaboratorioId = usutemp.LaboratorioId;
            validacion.CentrodecostoId = db.Centrodecostos.Where(c => c.SedeId == usutemp.SedeId).Select(i => i.CentrodecostoId).FirstOrDefault();
            validacion.Firmausuario1 = null;
            validacion.Firmausuario2 = null;

            return View(validacion);

        }

               
        //Post: Firmar validacion este metodo registra las firmas
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult FirmarValidacion(Validador validacion)
        {

            var autentic = User.Identity.IsAuthenticated;
            var nametemp = User.Identity.Name;
            var usutemp = db.Usuarios.Where(s => s.Logueo.Equals(nametemp)).FirstOrDefault();
                       
            var verificar = db.Validaciones.Where(u => u.UsuarioId == usutemp.Usuarioid).Select(f => f.Firmausuario1).FirstOrDefault();

            // se valida si existen las firmas y muestra un mensaje de error si existen
            if (verificar == null)
            {
                
                var valitemp = db.ValidadorDetalles.Where(u => u.UsuarioId == usutemp.Usuarioid).ToList();

                //se valida que si existan equipos validados
                if (valitemp.Count != 0)
                {

                    //se valida que si se hallan ingresado las firmas
                    if ((validacion.Firmausuario1Imagen != null && validacion.Firmausuario2Imagen != null))
                    {

                        var tam1 = validacion.Firmausuario1Imagen.ContentLength;
                        var tam2 = validacion.Firmausuario2Imagen.ContentLength;

                        // se valida que el tamaño de la imagen no sea exagerado
                        if ((tam1 < 7500) && (tam2 < 7500))
                        {

                            // en esta parte se suben las imagenes al seridor y se guarda la ruta en la base de datos
                            var firma1 = string.Empty;
                            var firma2 = string.Empty;
                            var folder = "~/Content/Firmas";

                            firma1 = MetodosHelper.SubirfFirma(validacion.Firmausuario1Imagen, folder);
                            firma1 = string.Format("{0}/{1}", folder, firma1);
                            firma2 = MetodosHelper.SubirfFirma(validacion.Firmausuario2Imagen, folder);
                            firma2 = string.Format("{0}/{1}", folder, firma2);

                            validacion.Firmausuario1 = firma1;
                            validacion.Firmausuario2 = firma2;

                            db.Entry(validacion).State = EntityState.Modified;

                            // en esta parte se carga toda la informacion para el reporte en la tabla de la base de datos, esta tabla es utilizada por el drystal reports
                            ReporteValidacion reportfinal = new ReporteValidacion();

                            var cabezatmp = db.Validaciones.Find(validacion.ValidadorId);

                            foreach (var tmp in db.ValidadorDetalles.Where(u => u.UsuarioId == usutemp.Usuarioid).ToList())
                            {

                                reportfinal.Sede = db.Sedes.Where(s => s.SedeId == cabezatmp.SedeId).Select(n => n.Nombre).FirstOrDefault();
                                reportfinal.Laboratorio = db.Laboratorios.Where(s => s.LaboratorioId == cabezatmp.LaboratorioId).Select(n => n.Nombre).FirstOrDefault();
                                reportfinal.Centro_de_costo = db.Centrodecostos.Where(s => s.CentrodecostoId == cabezatmp.CentrodecostoId).Select(n => n.Nombre).FirstOrDefault();
                                reportfinal.Identificador = db.Dispositivos.Where(d => d.DispositivoId == tmp.DispositivoId).Select(i => i.Identificador).FirstOrDefault();
                                reportfinal.Dispositivo = db.Dispositivos.Where(d => d.DispositivoId == tmp.DispositivoId).Select(i => i.Nombre).FirstOrDefault();
                                reportfinal.Precio = db.Dispositivos.Where(d => d.DispositivoId == tmp.DispositivoId).Select(i => i.Precio).FirstOrDefault();
                                reportfinal.Observaciones = db.Dispositivos.Where(d => d.DispositivoId == tmp.DispositivoId).Select(i => i.Observaciones).FirstOrDefault();
                                reportfinal.Estado_Validacion = db.Dispositivos.Where(d => d.DispositivoId == tmp.DispositivoId).Select(i => i.EstadoInventario).FirstOrDefault();
                                var tmpfecha = db.Dispositivos.Where(d => d.DispositivoId == tmp.DispositivoId).Select(i => i.Fecha).FirstOrDefault();

                                reportfinal.Fecha_compra = Convert.ToString(tmpfecha);

Inventory/Views/Validaciones/Create.cshtml
@model Inventory.Models.NuevaValidacionView
@{
    ViewBag.Title = "Validador";
}
<hr style="border-color:white" />
<h3>Validar inventario</h3>
@if (ViewBag.Message != null)
{

    <script type="text/javascript">window.onload = function () { alert("@ViewBag.Message"); };</script>
}




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr style="border-color:black" />

        <hr style="border-color:white" />
        @Html.ValidationSummary(true, "", new { @class = "text-success" })
        @Html.HiddenFor(model => model.Fechacompra)
        @Html.HiddenFor(model => model.Fecha)
        @Html.HiddenFor(model => model.ValidadetalleTmpId)

        <hr style="border-color:white" />
        <hr style="border-color:white" />
        <hr style="border-color:white" />


        <div class="row">
            <div class="col-md-2">

                <div class="form-group">
                   
                    <h4> @Html.LabelFor(model => model.DispoValidado, "Identificador ", htmlAttributes: new { @class = "control-label col-md-2" })</h4>


                </div>

            </div>
            <div class="col-md-4">

                <div class="form-group">
                    @Html.EditorFor(model => model.DispoValidado, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DispoValidado, "", new { @class = "text-danger" })


                </div>
            </div>

            <div class="col-md-4">

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Consultar" class="btn btn-default" />

                        @Html.ActionLink("Validar", "MostrarValidados", new { }, new { @class = "btn btn-primary" })


                    </div>
                </div>

            </div>

        </div>
    </div>


    ///////////////////////////////////////////////////////////////////////////
    <hr style="border-color:black" />
    <h3>Dispositivos validados</h3>
    <table class="table table-bordered table-striped mb-none" id="Validados">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Identificador)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Dispositivo)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Centrodecostos)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Fechacompra)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Costo)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Estado)
                </th>



                <th>
                    @Html.DisplayNameFor(model => model.EstadoInventario)
                </th>

            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model.ValiDetTmp)
            {
                <tr>

                    <th>
                        @Html.DisplayFor(modelItem => item.Identificador)
                    </th>
                    <th>
                        @Html.DisplayFor(modelItem => item.Dispositivo)
                    </th>
                    <th>
                        @Html.DisplayFor(modelItem => item.Centrodecostos)
                    </th>
                    <th>
                        @Html.DisplayFor(modelItem => item.Fechacompra)
                    </th>
                    <th>
                        @Html.DisplayFor(modelItem => item.Costo)
                    </th>
                    <th>
                        @Html.DisplayFor(modelItem => item.Estado)
                    </th>
                    @*<th>
                            Html.DisplayFor(modelItem => item.Observaciones)
                           Oservaciones: <input type="text" name="usrname" id="Observacion">

                        </th>*@
                    <th>
                        @Html.DisplayFor(modelItem => item.EstadoInventario)
                    </th>

                </tr>
            }
        </tbody>

    </table>

}










@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")




    @*<script type="text/javascript">
              $(document).ready(function () {
                  $("#DispoValidado").change(function () {
                      $("#Validados").empty();
                      $.ajax({
                            type: 'POST',
                            url: '@Url.Action("AgregarDispoValidado")',
                            dataType: 'json',
                            data: { dsp: $("#DispoValidado").val() },


                          success: function (data) {
                              var DatosJson = JSON.parse(JSON.stringify(data));

                              $("#Validados").append('<tr><td>Identificador</td>' +
                                  '<td>Dispositivo</td>' +
                                  '<td>Centro de costos</td>' + '<td>Fecha de compra</td>' +
                                  '<td>Precio</td>' +'<td>Estado</td>' +
                                  '<td>Observaciones</td>' + '<td>Estado Inventario</td>');
                              for (i = 0; i < DatosJson.length; i++) {

                                  $("#Validados").append('<tr>' +
                                      '<td>' + DatosJson.Identificador + '</td>' +
                                      '<td>' + DatosJson.Dispositivo + '</td>' +
                                      '<td>' + DatosJson.Centrodecostos + '</td>' +
                                      '<td>' + DatosJson.FechaCompra + '</td>' +
                                      '<td>' + DatosJson.Costo + '</td>' +
                                      '<td>' + DatosJson.Estado + '</td>' +
                                      '<td>' + DatosJson.Observaciones + '</td>' +
                                      '<td>' + DatosJson.EstadoInventario + '</td>' + '</tr>');
                              };
                          },


                                error: function (ex) {
                                    alert('Ocurrio una falla.' + ex);
                                }
                      });
                         return false;
                  })
              });








        </script>*@





}

Inventory/Views/Validaciones/Delete.cshtml
@model Inventory.Models.Validador

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Validador</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Estado.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Laboratorio.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Laboratorio.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sede.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sede.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Usuario.Logueo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usuario.Logueo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Firmausuario1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Firmausuario1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Firmausuario2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Firmausuario2)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Inventory/Views/Validaciones/Details.cshtml
@model Inventory.Models.Validador

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Validador</h4>
    <hr />
    <dl class="dl-horizontal">
      

        <dt>
            @Html.DisplayNameFor(model => model.Laboratorio.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Laboratorio.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sede.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sede.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Usuario.Logueo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usuario.Logueo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Firmausuario1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Firmausuario1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Firmausuario2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Firmausuario2)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ValidadorId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Inventory/Views/Validaciones/Edit.cshtml
@model Inventory.Models.ModelConfirmarView

@{
    ViewBag.Title = "Edit";
}
<hr style="border-color:white" />
<hr style="border-color:white" />
<h3>Observaciones del estado de inventario</h3>
@if (ViewBag.Message != null)
{

    <script type="text/javascript">window.onload = function () { alert("@ViewBag.Message"); };</script>
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr style="border-color:white" />

        <hr style="border-color:black" />
        <hr style="border-color:white" />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ValidadorDetalleId)
        @Html.HiddenFor(model => model.DispositivoId)
        @Html.HiddenFor(model => model.UsuarioId)
        @Html.HiddenFor(model => model.ValidadorId)
        <hr style="border-color:white" />
        <hr style="border-color:white" />


        <div class="row">
            <div class="col-md-2">
                <div class="form-group">
                    @*<div class="col-md-10">*@
                    <h4> @Html.LabelFor(model => model.Observaciones, htmlAttributes: new { @class = "control-label col-md-2" })</h4>
                    @*</div>*@
                </div>
            </div>

            <div class="col-md-3">
                <div class="form-group">
                    @*<div class="col-md-10">*@
                    @Html.EditorFor(model => model.Observaciones, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Observaciones, "", new { @class = "text-danger" })
                    @*</div>*@
                </div>
            </div>


            @*<div class="col-md-3">*@
            <div class="form-group">
                <div class="col-md-offset-2 col-md-3">
                    <input type="submit" value="Guardar" class="btn btn-primary" />
                    @Html.ActionLink("Regresar", "Index", new { }, new { @class = "btn btn-default" })
                </div>
            </div>
            @*</div>*@

        </div>
    </div>

}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Inventory/Views/Validaciones/FirmarValidacion.cshtml
@model Inventory.Models.Validador
@{
    ViewBag.Title = "FirmarValidacion";
}

<h2>Agregar firmas a la validacion</h2>
@if (ViewBag.Message != null)
{

    <script type="text/javascript">window.onload = function () { alert("@ViewBag.Message"); };</script>
}


@using (Html.BeginForm("FirmarValidacion", "Validaciones", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr style="border-color:black" />
        <hr style="border-color:white" />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ValidadorId)
        @Html.HiddenFor(model => model.UsuarioId)
        @Html.HiddenFor(model => model.Fecha)
        @Html.HiddenFor(model => model.CentrodecostoId)
        @Html.HiddenFor(model => model.LaboratorioId)
        @Html.HiddenFor(model => model.SedeId)
        <h2>Firmas</h2>
        <div class="row">
            <div class="col-md-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.Firmausuario1Imagen, "Primera", htmlAttributes: new { @class = "control-label col-md-2" })
                </div>


                <div class="form-group">

                    @Html.LabelFor(model => model.Firmausuario2Imagen, "Segunda", htmlAttributes: new { @class = "control-label col-md-2" })


                </div>
            </div>

            <div class="col-md-3">
                <div class="form-group">


                    <span class="btn btn-default btn-file">
                        @Html.TextBoxFor(modelo => modelo.Firmausuario1Imagen, new { type = "file" })
                    </span>

                    @*@Html.EditorFor(model => model.Firmausuario1, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Firmausuario1, "", new { @class = "text-danger" })*@

                </div>


                <div class="form-group">

                    <span class="btn btn-default btn-file">
                        @Html.TextBoxFor(modelo => modelo.Firmausuario2Imagen,"Seleccionar firma", new { type = "file" })
                    </span>

                    @*@Html.EditorFor(model => model.Firmausuario2, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Firmausuario2, "", new { @class = "text-danger" })*@


                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-3">
                    <div class="form-group">
                        <input type="submit" value="Guardar Firmas" class="btn btn-primary" target="_blank" />

                    </div>


                    <div class="form-group">
                        @Html.ActionLink("Exportar validacion", "PDF", new { }, new { @class = "btn btn-default", target = "_blank" })
                    </div>
                </div>
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Inventory/Views/Validaciones/Index.cshtml
@model IEnumerable<Inventory.Models.ValidadorDetalle>

@{
    ViewBag.Title = "Resumen";
}

<h2>Resumen de la validacion</h2>
@if (ViewBag.Message != null)
{

    <script type="text/javascript">window.onload = function () { alert("@ViewBag.Message"); };</script>
}



<div align="center">
    @Html.ActionLink("Firmar reporte de validacion", "FirmarValidacion", new { }, new { @class = "btn btn-primary" })
</div>
<hr style="border-color:black" />


<table class="table table-bordered table-striped mb-none" id="datatable-default">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Dispositivo.Identificador)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dispositivo.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dispositivo.Fecha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dispositivo.Precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dispositivo.Estado.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dispositivo.EstadoInventario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dispositivo.Observaciones)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Dispositivo.Identificador)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dispositivo.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dispositivo.Fecha)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dispositivo.Precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dispositivo.Estado.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dispositivo.EstadoInventario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dispositivo.Observaciones)
            </td>
            <td align="right">
                @Html.ActionLink("Observaciones", "Edit", new { id = item.ValidadorDetalleId }, new { @class = "btn btn-default" })

            </td>
        </tr>
    }

</table>